version: "3"

services:
  flask:
    build:
      context: ./app
    ports:
      - "8080"
    environment:
      - COMMIT_SHA=${COMMIT_SHA}
    networks:
      app_network:
        aliases:
          - flask-app

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
