name: CD 

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: configure credentials to s3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-west-1"
        
    - name: copy file from aws s3
      run: aws s3 cp s3://pp-app-infrastucture/ ./ --recursive
      if: success()
    
    - name: connect_to_server_and_apply_updates
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        USER_NAME : ubuntu
      run: |
        grep  public_ip ./pebble_infrastructure/terraform.tfstate | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" > connection-ip
        ls -la .
        ls -la ./pebble_infrastructure/
        export CONNECTION=$(cut -d= -f1 connection-ip )
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@$CONNECTION '
            #Now we have got the access of EC2 and we will start the deploy .
            cd /pp_application &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            export COMMIT_SHA=$(git rev-parse HEAD) &&
            docker-compose up -d --force-recreate
        '
      if: success()
